name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: make -C 3_Implementation/ all
    - name: run
      run: ./main --ci 3_Implementation/ all
